server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-3-34-144-29.ap-northeast-2.compute.amazonaws.com:8086/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: eureka-client-auth
          uri: lb://EUREKA-CLIENT-AUTH
          predicates:
            - Path=/api/v1/auth/**
        - id: auth-service-swagger
          uri: lb://EUREKA-CLIENT-AUTH
          predicates:
            - Path=/auth-service/**
        - id: eureka-client-common
          uri: lb://EUREKA-CLIENT-COMMON
          predicates:
            - Path=/api/v1/common/**
        - id: common-service-swagger
          uri: lb://EUREKA-CLIENT-COMMON
          predicates:
            - Path=/common-service/**
        - id: eureka-client-community
          uri: lb://EUREKA-CLIENT-COMMUNITY
          predicates:
            - Path=/api/v1/community/**
        - id: community-service-swagger
          uri: lb://EUREKA-CLIENT-COMMUNITY
          predicates:
            - Path=/community-service/**
        - id: eureka-client-recruit
          uri: lb://EUREKA-CLIENT-RECRUIT
          predicates:
            - Path=/api/v1/recruit/**
        - id: recruit-service-swagger
          uri: lb://EUREKA-CLIENT-RECRUIT
          predicates:
            - Path=/recruit-service/**
        - id: eureka-client-market
          uri: lb://EUREKA-CLIENT-MARKET
          predicates:
            - Path=/api/v1/market/**
        - id: market-service-swagger
          uri: lb://EUREKA-CLIENT-MARKET
          predicates:
            - Path=/market-service/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://ec2-3-34-144-29.ap-northeast-2.compute.amazonaws.com/"
              - "https://ec2-3-34-144-29.ap-northeast-2.compute.amazonaws.com/"
              - "http://localhost:3000/"
              - "https://localhost:3000/"
              - "http://localhost/"
              - "https://localhost/"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /common-service/swagger-ui/index.html
        name: Common
      - url: /community-service/swagger-ui/index.html
        name: Community
      - url: /recruit-service/swagger-ui/index.html
        name: Recruit
      - url: /market-service/swagger-ui/index.html
        name: Market
      - url: /auth-service/swagger-ui/index.html
        name: Auth
    use-root-path: true
