server:
  port: 8086

eureka:
  server:
    enable-self-preservation: false # 일시적인 네트워크 장애로 인한 서비스 해제 막기 위한 자기 보호모드 (default:true) 배포환경에선 반드시 true (false시 하트비트 미전송시 해당클라이언트 바로 제거)

  client:
    register-with-eureka: false # default:true 레지스트리에 자신을 등록할지에 대한 여부
    fetch-registry: false # default:true 레지스트리에 있는 정보를 가져올지에 대한 여부 -> true시 Eureka server 호출 대신 레지스트리가 로컬로 캐싱 -> eureka client가 30초마다 ereka 레지스트이 변경사항 여부 확인
    service-url:
      defaultZone: http://k10c108.p.ssafy.io:8086/eureka

spring:
  application:
    name: discovery-service
