# 배포용 yml
spring:
  servlet:
    multipart:
      maxFileSize: 5000MB
      maxRequestSize: 5000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k10c108.p.ssafy.io:3307/geulgrim?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      username: geulgrim
      password: ggc108
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    data:
      web:
        pageable:
          one-indexed-parameters: true