spring:
  profiles:
    active: dev
    include: skey
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k10c108.p.ssafy.io:3307/geulgeurim?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ssafy