# 개발용 yml
spring:
  servlet:
    multipart:
      maxFileSize: 5000MB
      maxRequestSize: 5000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geulgrim?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      username: geulgrim
      password: ggc108
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    data:
      web:
        pageable:
          one-indexed-parameters: true
  # mail push
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamgeulgrim@gmail.com
    password: fpua kxqz hjnp kyhn
    properties:
      mail:
        debug: true
        smtp:
          auth: false
          starttls:
            enable: true